name: Deploy

on:
  release:
    types: [published]

jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Plugin
        run: |
          bash bin/build.sh ${{ github.event.repository.name }}
        shell: bash

      # - name: Upload the archive as an artifact
      #   id: upload-plugin-artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ github.event.repository.name }}
      #     path: build
      - name: Add zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: build/${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
